### ISSUE TITLE
Build failure when running from x86_64

### ISSUE THREAD

**Issue by btharper** [Jason-ZW/os-raspberrypi#1]
Is this intended to be run from an existing arm64 host? Running make on my desktop fails with the message:
```
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
```
Would a PR to allow optional cross compilation be useful?

**Comment by Jason-ZW** [comment]
@btharper It is currently compiled on arm64. Valuable PR is very welcome.

**Comment by Jason-ZW** [comment]
Tested, build with no error. Need to verify the basic RancherOS functionality on the rpi.
Thanks.
